version: '{build}'
image: Visual Studio 2022

environment:
  SNKZIP_SECRET: #THE WARDEN OF THE NORTH
    secure: LhHqSu3rpTbi6HiAV7+QzATpBIdddl1bQjpUVhLOub7Ovgf6UHscWz3NSKlY9MQY

skip_commits:
  message: /(//skip\W*ci)|(read\W*me)/

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

build_script: build.cmd ci

test: off
# test_script:
#   - build.cmd citest

artifacts:
  - path: __package\*.nupkg
    name: NuGet
  - path: __package\*.snupkg
    name: Symbols
  - path: __package\*.zip
    name: Zip

nuget:
  disable_publish_on_pr: true

deploy:
    - provider: GitHub
      release: 'Release $(APPVEYOR_REPO_TAG_NAME) build $(APPVEYOR_BUILD_VERSION)'
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: '[**CHANGE LOG**](https://github.com/BitArmory/Turnstile/blob/master/HISTORY.md)'
      prerelease: $(IsPreRelease)
      artifact: Zip, NuGet, Symbols
      auth_token:
          secure: 6IYVNU+ZMER/LbYbvSxl7QkF0tesUx3j/qUc6rZqPjqLSNUHaUh1widD9SpmgVrGey6LirCJY5ZjE7kQRgNCg3iFcX7p1W23k80OWv8/tz0pokYqx2CC3uYPglBDFita
      on:
          branch: master
          appveyor_repo_tag_name: /v\d+\.\d+\.\d+/ 
          appveyor_repo_tag: true

    - provider: NuGet
      server:
      symbol_server:
      skip_symbols: false
      api_key:
          secure: QaoFWIEab9lUzpzhsMXCGXgeb9mCOrYI6ZZzm2sXDW3Jv2/VyKAOFI3ZpDHPQ1BT
      artifact: NuGet, Symbols
      on:
          branch: master
          appveyor_repo_tag_name: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true

on_failure:
    - ps: |
            # Enables RDP for debugging and setup some tools
            # $blockRdp = $true; choco install notepad2; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
            
