// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct("BitArmory.Turnstile")]
[assembly: AssemblyTitle("BitArmory.Turnstile for .NET")]
[assembly: AssemblyCompany("Bit Armory Inc")]
[assembly: AssemblyCopyright("Bit Armory Inc © 2015")]
[assembly: AssemblyVersion("0.0.0")]
[assembly: AssemblyFileVersion("0.0.0")]
[assembly: AssemblyInformationalVersion("0.0.0-localbuild built on 2015-01-01 00:00:00Z UTC")]
[assembly: AssemblyTrademark("MIT License")]
[assembly: AssemblyDescription("https://github.com/BitArmory/Turnstile")]
[assembly: InternalsVisibleTo("BitArmory.Turnstile.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "BitArmory.Turnstile";
        internal const System.String AssemblyTitle = "BitArmory.Turnstile for .NET";
        internal const System.String AssemblyCompany = "Bit Armory Inc";
        internal const System.String AssemblyCopyright = "Bit Armory Inc © 2015";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 2015-01-01 00:00:00Z UTC";
        internal const System.String AssemblyTrademark = "MIT License";
        internal const System.String AssemblyDescription = "https://github.com/BitArmory/Turnstile";
        internal const System.String InternalsVisibleTo = "BitArmory.Turnstile.Tests";
    }
}
